version = 0.1

[default]
stack_name = "my-stack-name"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j3asoy1ivf35"
resolve_s3 = false

[default.deploy.parameters]
stack_name = "tsmonorepo"
resolve_s3 = true
s3_prefix = "tsmonorepo"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
